version: '0.2'
phases:
  install:
    runtime-versions:
      dotnet: '3.1'
    commands:
      # install the CodeArtifact Credential Provider
      - 'export PATH="$PATH:/root/.dotnet/tools"'
      - dotnet tool install --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources -g AWS.CodeArtifact.NuGet.CredentialProvider
      - dotnet codeartifact-creds install
  build:
    commands:
      # push your NuGet package to CodeArtifact
      - PACKAGE_VERSION="1.0.0"
      - dotnet pack -c Release /p:Version="$PACKAGE_VERSION"
      - dotnet nuget push -k aws "bin/Release/SampleOrg.SampleLib.${PACKAGE_VERSION}.nupkg"